#!/bin/sh
# Arguments:
#   $1 - Name to give to the solution.

if [ $# -eq 0 ]; then
  echo "add_sln <name of the problem>"
  exit -1
fi

set -e

name=$1
cp sol.cc sln/$name.cc
git add sln/$name.cc
git add sol.cc
git status -s -uno
git ci -m "$name"
