#!/bin/sh
if [ ! $1 ]; then
  echo "Usage:
  build <C++11 source file name>"
  exit -1
fi

if [ $(uname) = "Darwin" ]; then
  cc=clang++
else
  cc=g++
fi

src=$1
output=${src%.*}  # Extension trimmed.

rm -rf $output $output.dSYM

dbg="-O0 -g -DDEBUG"
opt="-O2 -flto -ffast-math -DNDEBUG"
mode=$dbg
warnings="-Wall -Wno-unused-function -Wno-unused-result"
$cc -std=c++0x -march=native $mode $warnings $src -o $output -lm -lstdc++
