#!/bin/sh
set -u

if [ $# -ne 1 ]; then
  echo "Usage:
  run <C++11 source file name>"
  exit -1
fi

src=$1
set +e
./build ${src}
set -e
output=${src%.*}.bin  # Extension trimmed.
if [ $? -eq 0 ]; then
  ./${output} < sol.in
fi
