#!/bin/sh
set -u

if [ ! $1 ]; then
  echo "Usage:
  run <C++11 source file name>"
  exit -1
fi

src=$1
set +e
./build ${src}
set -e
if [ $? -eq 0 ]; then
  output=${src%.*}  # Extension trimmed.
  ./${output} < sol.in
fi
