#! /bin/sh

echo > owlc.stdout
echo > owlc.stderr
for owl in $(find tests/ -name '*.owl' | sort); do
  echo 'INPUT:' $owl >> owlc.stdout
  echo 'INPUT:' $owl >> owlc.stderr
  cat $owl >> owlc.stderr
  ./owlc $owl 1>>owlc.stdout 2>>owlc.stderr
  ec=$?
  echo "EXIT CODE: $ec\n" >> owlc.stdout
  echo "EXIT CODE: $ec\n" >> owlc.stderr
done
cmp -s tests/owlc.stdout owlc.stdout || { echo 'stdout diff' && exit 1; }
cmp -s tests/owlc.stderr owlc.stderr || { echo 'stderr diff' && exit 1; }
echo 'ALL TESTS PASSED'
