#!/bin/sh
find . -name '*_test' -executable -type f -exec {} \;

stdout=report_stdout
stderr=report_stderr
echo > $stdout
echo > $stderr
for owl in $(find tests/ -name '*.owl' | sort); do
  echo 'INPUT:' $owl >> $stdout
  echo 'INPUT:' $owl >> $stderr
  cat $owl >> $stderr
  ./owlc $owl 1>>$stdout 2>>$stderr
  ec=$?
  echo "EXIT CODE: $ec\n" >> $stdout
  echo "EXIT CODE: $ec\n" >> $stderr
done
cmp -s tests/$stdout $stdout || { echo "$stdout diff" && exit 1; }
cmp -s tests/$stderr $stderr || { echo "$stderr diff" && exit 1; }
echo 'TEST SUITE TESTS PASSED'
