<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Webhome</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
</head>
<body>
<div>
  <img src="res/logo.png" alt="Sample Image"/>
  <form action="/newpost" method="post">
    <div>
      <input type="text" name="text"/>
      <input type="submit" value="Tweet"/>
    </div>
  </form>
<div>
$text$
</div>
<div>
  <a href="/wallet">Wallet</a>
</div>
<div>
$auth$
</div>
</div>
</body>
</html>
