/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package owl.lang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int O = 15;
  /** RegularExpression Id. */
  int D = 16;
  /** RegularExpression Id. */
  int H = 17;
  /** RegularExpression Id. */
  int NF = 18;
  /** RegularExpression Id. */
  int TF = 19;
  /** RegularExpression Id. */
  int L = 20;
  /** RegularExpression Id. */
  int NUM_DEC = 21;
  /** RegularExpression Id. */
  int NUM_HEX = 22;
  /** RegularExpression Id. */
  int NUM_OCT = 23;
  /** RegularExpression Id. */
  int NAME = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"as\"",
    "\"fn\"",
    "\".\"",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<O>",
    "<D>",
    "<H>",
    "<NF>",
    "<TF>",
    "<L>",
    "<NUM_DEC>",
    "<NUM_HEX>",
    "<NUM_OCT>",
    "<NAME>",
  };

}
