/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package owl.lang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AS = 5;
  /** RegularExpression Id. */
  int FN = 6;
  /** RegularExpression Id. */
  int O = 19;
  /** RegularExpression Id. */
  int D = 20;
  /** RegularExpression Id. */
  int H = 21;
  /** RegularExpression Id. */
  int NAME_FIRST = 22;
  /** RegularExpression Id. */
  int META_FIRST = 23;
  /** RegularExpression Id. */
  int L = 24;
  /** RegularExpression Id. */
  int NUM_DEC = 25;
  /** RegularExpression Id. */
  int NUM_HEX = 26;
  /** RegularExpression Id. */
  int NUM_OCT = 27;
  /** RegularExpression Id. */
  int NAME = 28;
  /** RegularExpression Id. */
  int META = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"as\"",
    "\"fn\"",
    "\".\"",
    "\",\"",
    "\"_\"",
    "\":\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=>\"",
    "<O>",
    "<D>",
    "<H>",
    "<NAME_FIRST>",
    "<META_FIRST>",
    "<L>",
    "<NUM_DEC>",
    "<NUM_HEX>",
    "<NUM_OCT>",
    "<NAME>",
    "<META>",
  };

}
