#! /bin/bash

# set -e

function rcopy() {
  cp -R ~/$1 $(dirname $1)
}

function find_rm() {
  find -iname $1 -exec rm -rf {} \; 2> /dev/null
}

rcopy '.bashrc'
rcopy '.i3'
rcopy '.i3status.conf'
rcopy '.tmux.conf'
rcopy '.vimrc'
rcopy '.Xmodmap'
rcopy '.config/gtk-3.0/settings.ini'
rcopy '.config/sublime-text-2'
rcopy '.config/terminator'

find_rm '*.cache'
find_rm '*.sublime_session'
find_rm '*.last-run'
find_rm '*.pyc'

